"""Initial

Revision ID: f3a390000133
Revises:
Create Date: 2025-11-23 02:46:51.387303

"""

from typing import Any, Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migration.helpers import get_query_for_bulk_insert
from models.deal_stage_models import DEAL_STAGE_VALUES


def bulk_insert(
    table_name: str, columns: list[str], data: list[tuple[Any, ...]]
) -> None:
    """
    Универсальная функция для вставки данных
    :param table_name: Имя таблицы
    :param columns: Список колонок
    :param data: Итерируемый объект с кортежами данных
    """
    query = get_query_for_bulk_insert(table_name, columns, data)
    op.execute(sa.text(query))


# revision identifiers, used by Alembic.
revision: str = "f3a390000133"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "communication_channel_types",
        sa.Column(
            "type_id",
            sa.String(length=20),
            nullable=False,
            comment="Тип коммуникации",
        ),
        sa.Column(
            "value_type",
            sa.String(length=50),
            nullable=False,
            comment="Уточнение типа коммуникации по каналу",
        ),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=True,
            comment="Описание типа канала",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "type_id", "value_type", name="uq_channel_type_value_type"
        ),
    )
    op.create_table(
        "deal_stages",
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=False,
            comment="Порядковый номер стадии",
        ),
        sa.Column(
            "external_id",
            sa.String(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="Название"),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("sort_order"),
    )
    op.create_table(
        "departments",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False, comment="Название"),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["departments.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "communication_channels",
        sa.Column(
            "entity_type",
            sa.String(length=20),
            nullable=False,
            comment="Тип сущности",
        ),
        sa.Column(
            "entity_id",
            sa.Integer(),
            nullable=False,
            comment="Внешний ID соответствующей сущности",
        ),
        sa.Column("channel_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "value",
            sa.String(length=255),
            nullable=False,
            comment="Значение коннекта",
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["channel_type_id"],
            ["communication_channel_types.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(
        op.f("ix_communication_channels_entity_type"),
        "communication_channels",
        ["entity_type"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("xml_id", sa.String(), nullable=True, comment="Внешний код"),
        sa.Column("name", sa.String(), nullable=True, comment="Имя"),
        sa.Column(
            "second_name", sa.String(), nullable=True, comment="Отчество"
        ),
        sa.Column("last_name", sa.String(), nullable=True, comment="Фамилия"),
        sa.Column(
            "personal_gender", sa.String(), nullable=True, comment="Пол"
        ),
        sa.Column(
            "work_position", sa.String(), nullable=True, comment="Должность"
        ),
        sa.Column(
            "user_type", sa.String(), nullable=True, comment="Тип пользователя"
        ),
        sa.Column(
            "active", sa.Boolean(), nullable=False, comment="Активность"
        ),
        sa.Column("is_online", sa.Boolean(), nullable=False, comment="Онлайн"),
        sa.Column(
            "last_login",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Последняя авторизация",
        ),
        sa.Column(
            "date_register",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата регистрации",
        ),
        sa.Column(
            "personal_birthday",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата рождения",
        ),
        sa.Column(
            "employment_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Новая дата",
        ),
        sa.Column(
            "date_new",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Новая дата",
        ),
        sa.Column(
            "time_zone", sa.String(), nullable=True, comment="Часовой пояс"
        ),
        sa.Column(
            "personal_city",
            sa.String(),
            nullable=True,
            comment="Город проживания",
        ),
        sa.Column("email", sa.String(), nullable=True, comment="E-Mail"),
        sa.Column(
            "personal_mobile",
            sa.String(),
            nullable=True,
            comment="Личный мобильный",
        ),
        sa.Column(
            "work_phone",
            sa.String(),
            nullable=True,
            comment="Телефон компании",
        ),
        sa.Column(
            "personal_www",
            sa.String(),
            nullable=True,
            comment="Домашняя страничка",
        ),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "companies",
        sa.Column(
            "title", sa.String(), nullable=False, comment="Название сделки"
        ),
        sa.Column(
            "origin_version",
            sa.String(),
            nullable=True,
            comment="Версия данных о контакте во внешней системе",
        ),
        sa.Column(
            "employees",
            sa.String(),
            nullable=True,
            comment="Численность сотрудников",
        ),
        sa.Column(
            "banking_details",
            sa.String(),
            nullable=True,
            comment="Банковские реквизиты",
        ),
        sa.Column(
            "revenue", sa.Float(), nullable=False, comment="Годовой оборот"
        ),
        sa.Column(
            "address_legal",
            sa.String(),
            nullable=True,
            comment="Юридический адрес",
        ),
        sa.Column(
            "is_my_company",
            sa.Boolean(),
            nullable=False,
            comment="Моя компания",
        ),
        sa.Column(
            "originator_id",
            sa.String(),
            nullable=True,
            comment="ID источника данных",
        ),
        sa.Column(
            "origin_id",
            sa.String(),
            nullable=True,
            comment="ID элемента в источнике",
        ),
        sa.Column(
            "comments", sa.String(), nullable=True, comment="Комментарии"
        ),
        sa.Column(
            "source_description",
            sa.String(),
            nullable=True,
            comment="Описание источника",
        ),
        sa.Column(
            "opened", sa.Boolean(), nullable=False, comment="Доступна для всех"
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.Column(
            "date_create",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "date_modify",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата изменения",
        ),
        sa.Column(
            "last_activity_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время последней активности",
        ),
        sa.Column(
            "last_communication_time",
            sa.DateTime(),
            nullable=True,
            comment="Время последней коммуникации",
        ),
        sa.Column(
            "assigned_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID ответственного",
        ),
        sa.Column(
            "created_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID создателя",
        ),
        sa.Column(
            "modify_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID изменившего",
        ),
        sa.Column(
            "last_activity_by",
            sa.Integer(),
            nullable=True,
            comment="ID последней активности",
        ),
        sa.Column(
            "utm_source",
            sa.String(),
            nullable=True,
            comment="Рекламная система",
        ),
        sa.Column(
            "utm_medium", sa.String(), nullable=True, comment="Тип трафика"
        ),
        sa.Column(
            "utm_campaign",
            sa.String(),
            nullable=True,
            comment="Обозначение рекламной кампании",
        ),
        sa.Column(
            "utm_content",
            sa.String(),
            nullable=True,
            comment="Содержание кампании",
        ),
        sa.Column(
            "utm_term", sa.String(), nullable=True, comment="Тип трафика"
        ),
        sa.Column(
            "has_phone",
            sa.Boolean(),
            nullable=False,
            comment="Признак заполненности поля\xa0телефон",
        ),
        sa.Column(
            "has_email",
            sa.Boolean(),
            nullable=False,
            comment="Признак заполненности электронной почты",
        ),
        sa.Column(
            "has_imol",
            sa.Boolean(),
            nullable=False,
            comment="Признак наличия привязанной открытой линии",
        ),
        sa.Column(
            "address", sa.String(), nullable=True, comment="Адрес контакта"
        ),
        sa.Column(
            "address_2",
            sa.String(),
            nullable=True,
            comment="Вторая страница адреса",
        ),
        sa.Column("address_city", sa.String(), nullable=True, comment="Город"),
        sa.Column(
            "address_postal_code",
            sa.String(),
            nullable=True,
            comment="Почтовый индекс",
        ),
        sa.Column(
            "address_region", sa.String(), nullable=True, comment="Район"
        ),
        sa.Column(
            "address_province", sa.String(), nullable=True, comment="Область"
        ),
        sa.Column(
            "address_country", sa.String(), nullable=True, comment="Страна"
        ),
        sa.Column(
            "address_country_code",
            sa.String(),
            nullable=True,
            comment="Код страны",
        ),
        sa.Column(
            "address_loc_addr_id",
            sa.Integer(),
            nullable=True,
            comment="Идентификатор адреса из модуля местоположений",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_activity_by"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["modify_by_id"],
            ["users.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "contacts",
        sa.Column("name", sa.String(), nullable=True, comment="Имя контакта"),
        sa.Column(
            "second_name",
            sa.String(),
            nullable=True,
            comment="Отчество контакта",
        ),
        sa.Column(
            "last_name", sa.String(), nullable=True, comment="Фамилия контакта"
        ),
        sa.Column("post", sa.String(), nullable=True, comment="Должность"),
        sa.Column(
            "origin_version",
            sa.String(),
            nullable=True,
            comment="Версия данных о контакте во внешней системе",
        ),
        sa.Column(
            "export",
            sa.Boolean(),
            nullable=False,
            comment="Участвует в экспорте контактов",
        ),
        sa.Column(
            "birthdate",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата рождения",
        ),
        sa.Column(
            "type_id", sa.String(), nullable=True, comment="Тип контакта"
        ),
        sa.Column(
            "company_id", sa.Integer(), nullable=True, comment="Ид компании"
        ),
        sa.Column("lead_id", sa.Integer(), nullable=True, comment="Ид лида"),
        sa.Column(
            "source_id",
            sa.String(),
            nullable=True,
            comment="Идентификатор источника",
        ),
        sa.Column(
            "originator_id",
            sa.String(),
            nullable=True,
            comment="ID источника данных",
        ),
        sa.Column(
            "origin_id",
            sa.String(),
            nullable=True,
            comment="ID элемента в источнике",
        ),
        sa.Column(
            "comments", sa.String(), nullable=True, comment="Комментарии"
        ),
        sa.Column(
            "source_description",
            sa.String(),
            nullable=True,
            comment="Описание источника",
        ),
        sa.Column(
            "opened", sa.Boolean(), nullable=False, comment="Доступна для всех"
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.Column(
            "date_create",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "date_modify",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата изменения",
        ),
        sa.Column(
            "last_activity_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время последней активности",
        ),
        sa.Column(
            "last_communication_time",
            sa.DateTime(),
            nullable=True,
            comment="Время последней коммуникации",
        ),
        sa.Column(
            "assigned_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID ответственного",
        ),
        sa.Column(
            "created_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID создателя",
        ),
        sa.Column(
            "modify_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID изменившего",
        ),
        sa.Column(
            "last_activity_by",
            sa.Integer(),
            nullable=True,
            comment="ID последней активности",
        ),
        sa.Column(
            "utm_source",
            sa.String(),
            nullable=True,
            comment="Рекламная система",
        ),
        sa.Column(
            "utm_medium", sa.String(), nullable=True, comment="Тип трафика"
        ),
        sa.Column(
            "utm_campaign",
            sa.String(),
            nullable=True,
            comment="Обозначение рекламной кампании",
        ),
        sa.Column(
            "utm_content",
            sa.String(),
            nullable=True,
            comment="Содержание кампании",
        ),
        sa.Column(
            "utm_term", sa.String(), nullable=True, comment="Тип трафика"
        ),
        sa.Column(
            "has_phone",
            sa.Boolean(),
            nullable=False,
            comment="Признак заполненности поля\xa0телефон",
        ),
        sa.Column(
            "has_email",
            sa.Boolean(),
            nullable=False,
            comment="Признак заполненности электронной почты",
        ),
        sa.Column(
            "has_imol",
            sa.Boolean(),
            nullable=False,
            comment="Признак наличия привязанной открытой линии",
        ),
        sa.Column(
            "address", sa.String(), nullable=True, comment="Адрес контакта"
        ),
        sa.Column(
            "address_2",
            sa.String(),
            nullable=True,
            comment="Вторая страница адреса",
        ),
        sa.Column("address_city", sa.String(), nullable=True, comment="Город"),
        sa.Column(
            "address_postal_code",
            sa.String(),
            nullable=True,
            comment="Почтовый индекс",
        ),
        sa.Column(
            "address_region", sa.String(), nullable=True, comment="Район"
        ),
        sa.Column(
            "address_province", sa.String(), nullable=True, comment="Область"
        ),
        sa.Column(
            "address_country", sa.String(), nullable=True, comment="Страна"
        ),
        sa.Column(
            "address_country_code",
            sa.String(),
            nullable=True,
            comment="Код страны",
        ),
        sa.Column(
            "address_loc_addr_id",
            sa.Integer(),
            nullable=True,
            comment="Идентификатор адреса из модуля местоположений",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_activity_by"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["modify_by_id"],
            ["users.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "leads",
        sa.Column(
            "title", sa.String(), nullable=False, comment="Название лида"
        ),
        sa.Column("name", sa.String(), nullable=True, comment="Имя контакта"),
        sa.Column(
            "second_name",
            sa.String(),
            nullable=True,
            comment="Отчество контакта",
        ),
        sa.Column(
            "last_name", sa.String(), nullable=True, comment="Фамилия контакта"
        ),
        sa.Column("post", sa.String(), nullable=True, comment="Должность"),
        sa.Column(
            "company_title",
            sa.String(),
            nullable=True,
            comment="Название компании, привязанной к лиду",
        ),
        sa.Column(
            "is_manual_opportunity",
            sa.Boolean(),
            nullable=False,
            comment="Ручной ввод суммы",
        ),
        sa.Column(
            "is_return_customer",
            sa.Boolean(),
            nullable=False,
            comment="Повторный клиент",
        ),
        sa.Column(
            "opportunity", sa.Float(), nullable=False, comment="Сумма сделки"
        ),
        sa.Column(
            "birthdate",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата рождения",
        ),
        sa.Column(
            "moved_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время перемещения",
        ),
        sa.Column(
            "date_closed",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата закрытия",
        ),
        sa.Column(
            "status_semantic_id",
            postgresql.ENUM(
                "PROSPECTIVE", "SUCCESS", "FAIL", name="deal_stage_enum"
            ),
            nullable=False,
            comment="Семантика стадии",
        ),
        sa.Column(
            "currency_id", sa.String(), nullable=True, comment="Ид валюты"
        ),
        sa.Column(
            "status_id",
            sa.String(),
            nullable=False,
            comment="Идентификатор стадии лида",
        ),
        sa.Column(
            "company_id", sa.Integer(), nullable=True, comment="Ид компании"
        ),
        sa.Column(
            "contact_id", sa.Integer(), nullable=True, comment="Ид контакта"
        ),
        sa.Column(
            "source_id",
            sa.String(),
            nullable=True,
            comment="Идентификатор источника (сводно)",
        ),
        sa.Column(
            "moved_by_id",
            sa.Integer(),
            nullable=True,
            comment="ID переместившего",
        ),
        sa.Column(
            "originator_id",
            sa.String(),
            nullable=True,
            comment="ID источника данных",
        ),
        sa.Column(
            "origin_id",
            sa.String(),
            nullable=True,
            comment="ID элемента в источнике",
        ),
        sa.Column(
            "comments", sa.String(), nullable=True, comment="Комментарии"
        ),
        sa.Column(
            "source_description",
            sa.String(),
            nullable=True,
            comment="Описание источника",
        ),
        sa.Column(
            "opened", sa.Boolean(), nullable=False, comment="Доступна для всех"
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.Column(
            "date_create",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "date_modify",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата изменения",
        ),
        sa.Column(
            "last_activity_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время последней активности",
        ),
        sa.Column(
            "last_communication_time",
            sa.DateTime(),
            nullable=True,
            comment="Время последней коммуникации",
        ),
        sa.Column(
            "assigned_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID ответственного",
        ),
        sa.Column(
            "created_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID создателя",
        ),
        sa.Column(
            "modify_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID изменившего",
        ),
        sa.Column(
            "last_activity_by",
            sa.Integer(),
            nullable=True,
            comment="ID последней активности",
        ),
        sa.Column(
            "utm_source",
            sa.String(),
            nullable=True,
            comment="Рекламная система",
        ),
        sa.Column(
            "utm_medium", sa.String(), nullable=True, comment="Тип трафика"
        ),
        sa.Column(
            "utm_campaign",
            sa.String(),
            nullable=True,
            comment="Обозначение рекламной кампании",
        ),
        sa.Column(
            "utm_content",
            sa.String(),
            nullable=True,
            comment="Содержание кампании",
        ),
        sa.Column(
            "utm_term", sa.String(), nullable=True, comment="Тип трафика"
        ),
        sa.Column(
            "has_phone",
            sa.Boolean(),
            nullable=False,
            comment="Признак заполненности поля\xa0телефон",
        ),
        sa.Column(
            "has_email",
            sa.Boolean(),
            nullable=False,
            comment="Признак заполненности электронной почты",
        ),
        sa.Column(
            "has_imol",
            sa.Boolean(),
            nullable=False,
            comment="Признак наличия привязанной открытой линии",
        ),
        sa.Column(
            "address", sa.String(), nullable=True, comment="Адрес контакта"
        ),
        sa.Column(
            "address_2",
            sa.String(),
            nullable=True,
            comment="Вторая страница адреса",
        ),
        sa.Column("address_city", sa.String(), nullable=True, comment="Город"),
        sa.Column(
            "address_postal_code",
            sa.String(),
            nullable=True,
            comment="Почтовый индекс",
        ),
        sa.Column(
            "address_region", sa.String(), nullable=True, comment="Район"
        ),
        sa.Column(
            "address_province", sa.String(), nullable=True, comment="Область"
        ),
        sa.Column(
            "address_country", sa.String(), nullable=True, comment="Страна"
        ),
        sa.Column(
            "address_country_code",
            sa.String(),
            nullable=True,
            comment="Код страны",
        ),
        sa.Column(
            "address_loc_addr_id",
            sa.Integer(),
            nullable=True,
            comment="Идентификатор адреса из модуля местоположений",
        ),
        sa.CheckConstraint(
            "opportunity >= 0", name="non_negative_opportunity"
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_activity_by"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["modify_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["moved_by_id"],
            ["users.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "managers",
        sa.Column(
            "user_id", sa.Integer(), nullable=False, comment="ИД сотрудника"
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Менеджер активный",
        ),
        sa.Column("disk_id", sa.Integer(), nullable=True, comment="ИД диска"),
        sa.Column(
            "chat_id",
            sa.Integer(),
            nullable=True,
            comment="ИД служебного чата",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "timeline_comments",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата добавления",
        ),
        sa.Column(
            "entity_id",
            sa.Integer(),
            nullable=False,
            comment="ID элемента, к которому привязан комментарий",
        ),
        sa.Column(
            "entity_type",
            sa.String(length=20),
            nullable=False,
            comment="Тип элемента, к которому привязан комментарий",
        ),
        sa.Column("author_id", sa.Integer(), nullable=True, comment="Автор"),
        sa.Column(
            "comment_entity",
            sa.String(),
            nullable=True,
            comment="Текст комментария",
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "deals",
        sa.Column(
            "title", sa.String(), nullable=False, comment="Название сделки"
        ),
        sa.Column(
            "additional_info",
            sa.String(),
            nullable=True,
            comment="Дополнительная информация",
        ),
        sa.Column(
            "repeat_sale_segment_id",
            sa.String(),
            nullable=True,
            comment="Сегмент повторных продаж",
        ),
        sa.Column(
            "introduction_offer",
            sa.String(),
            nullable=True,
            comment="Представление в КП",
        ),
        sa.Column(
            "location_id",
            sa.String(),
            nullable=True,
            comment="Расположение ИД",
        ),
        sa.Column(
            "delivery_days",
            sa.Integer(),
            nullable=True,
            comment="Срок поставки (дни)",
        ),
        sa.Column(
            "warranty_months",
            sa.Integer(),
            nullable=True,
            comment="Гарантия (мес)",
        ),
        sa.Column("contract", sa.String(), nullable=True, comment="Договор"),
        sa.Column(
            "begining_condition_payment_percentage",
            sa.Integer(),
            nullable=True,
            comment="Процент оплаты для начала сделки",
        ),
        sa.Column(
            "shipping_condition_payment_percentage",
            sa.Integer(),
            nullable=True,
            comment="Процент оплаты для отгрузки сделки",
        ),
        sa.Column(
            "probability",
            sa.Integer(),
            nullable=True,
            comment="Вероятность успеха (0-100)",
        ),
        sa.Column(
            "is_manual_opportunity",
            sa.Boolean(),
            nullable=False,
            comment="Ручной ввод суммы",
        ),
        sa.Column("closed", sa.Boolean(), nullable=False, comment="Завершена"),
        sa.Column(
            "is_new", sa.Boolean(), nullable=False, comment="Новая сделка"
        ),
        sa.Column(
            "is_recurring",
            sa.Boolean(),
            nullable=False,
            comment="Регулярная сделка",
        ),
        sa.Column(
            "is_return_customer",
            sa.Boolean(),
            nullable=False,
            comment="Повторный клиент",
        ),
        sa.Column(
            "is_repeated_approach",
            sa.Boolean(),
            nullable=False,
            comment="Повторное обращение",
        ),
        sa.Column(
            "without_offer", sa.Boolean(), nullable=True, comment="Без КП"
        ),
        sa.Column(
            "without_contract",
            sa.Boolean(),
            nullable=True,
            comment="Без договора",
        ),
        sa.Column(
            "opportunity", sa.Float(), nullable=False, comment="Сумма сделки"
        ),
        sa.Column("tax_value", sa.Float(), nullable=True, comment="Сумма НДС"),
        sa.Column(
            "half_amount", sa.Float(), nullable=True, comment="Половино суммы"
        ),
        sa.Column(
            "begindate",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата начала",
        ),
        sa.Column(
            "closedate",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата завершения",
        ),
        sa.Column(
            "moved_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время перемещения",
        ),
        sa.Column(
            "date_answer_client",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Ожидаемая дата ответа от клиента",
        ),
        sa.Column(
            "stage_semantic_id",
            postgresql.ENUM(
                "PROSPECTIVE", "SUCCESS", "FAIL", name="deal_stage_enum"
            ),
            nullable=False,
            comment="Семантика стадии",
        ),
        sa.Column(
            "status_deal",
            postgresql.ENUM(
                "NEW",
                "ACCEPTED",
                "OFFER_NO",
                "OFFER_IN_AGREEMENT_SUPERVISOR",
                "OFFER_APPROVED_SUPERVISOR",
                "OFFER_DISMISSED_SUPERVISOR",
                "OFFER_SENT_CLIENT",
                "OFFER_APPROVED_CLIENT",
                "OFFER_DISMISSED_CLIENT",
                "NOT_DEFINE",
                name="deal_status_enum",
            ),
            nullable=False,
            comment="Статус обработки",
        ),
        sa.Column(
            "currency_id", sa.String(), nullable=True, comment="Ид валюты"
        ),
        sa.Column("type_id", sa.String(), nullable=True, comment="Тип сделки"),
        sa.Column("stage_id", sa.String(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=False,
            comment="Идентификатор направления",
        ),
        sa.Column(
            "source_id",
            sa.String(),
            nullable=True,
            comment="Идентификатор источника",
        ),
        sa.Column(
            "quote_id", sa.Integer(), nullable=True, comment="Предложение"
        ),
        sa.Column(
            "offer_link", sa.String(), nullable=True, comment="Ссылка на КП"
        ),
        sa.Column(
            "moved_by_id",
            sa.Integer(),
            nullable=True,
            comment="ID переместившего",
        ),
        sa.Column(
            "wz_instagram", sa.String(), nullable=True, comment="Инстаграм"
        ),
        sa.Column("wz_vc", sa.String(), nullable=True, comment="ВК"),
        sa.Column(
            "wz_telegram_username",
            sa.String(),
            nullable=True,
            comment="Телеграм имя",
        ),
        sa.Column(
            "wz_telegram_id", sa.String(), nullable=True, comment="Телеграм ИД"
        ),
        sa.Column("wz_avito", sa.String(), nullable=True, comment="Авито"),
        sa.Column("wz_maxid", sa.String(), nullable=True, comment="Макс"),
        sa.Column(
            "moved_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Дата перемещения (резервное поле)",
        ),
        sa.Column(
            "originator_id",
            sa.String(),
            nullable=True,
            comment="ID источника данных",
        ),
        sa.Column(
            "origin_id",
            sa.String(),
            nullable=True,
            comment="ID элемента в источнике",
        ),
        sa.Column(
            "comments", sa.String(), nullable=True, comment="Комментарии"
        ),
        sa.Column(
            "source_description",
            sa.String(),
            nullable=True,
            comment="Описание источника",
        ),
        sa.Column(
            "opened", sa.Boolean(), nullable=False, comment="Доступна для всех"
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.Column(
            "date_create",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "date_modify",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата изменения",
        ),
        sa.Column(
            "last_activity_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время последней активности",
        ),
        sa.Column(
            "last_communication_time",
            sa.DateTime(),
            nullable=True,
            comment="Время последней коммуникации",
        ),
        sa.Column(
            "assigned_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID ответственного",
        ),
        sa.Column(
            "created_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID создателя",
        ),
        sa.Column(
            "modify_by_id",
            sa.Integer(),
            nullable=False,
            comment="ID изменившего",
        ),
        sa.Column(
            "last_activity_by",
            sa.Integer(),
            nullable=True,
            comment="ID последней активности",
        ),
        sa.Column(
            "utm_source",
            sa.String(),
            nullable=True,
            comment="Рекламная система",
        ),
        sa.Column(
            "utm_medium", sa.String(), nullable=True, comment="Тип трафика"
        ),
        sa.Column(
            "utm_campaign",
            sa.String(),
            nullable=True,
            comment="Обозначение рекламной кампании",
        ),
        sa.Column(
            "utm_content",
            sa.String(),
            nullable=True,
            comment="Содержание кампании",
        ),
        sa.Column(
            "utm_term", sa.String(), nullable=True, comment="Тип трафика"
        ),
        sa.CheckConstraint("external_id > 0", name="external_id_positive"),
        sa.CheckConstraint(
            "opportunity >= 0", name="non_negative_opportunity"
        ),
        sa.CheckConstraint(
            "probability IS NULL OR (probability BETWEEN 0 AND 100)",
            name="valid_probability_range",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_activity_by"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["modify_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["moved_by_id"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["deal_stages.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "additional_info",
        sa.Column(
            "deal_id", sa.Integer(), nullable=False, comment="ID сделки"
        ),
        sa.Column(
            "comment",
            sa.String(),
            nullable=False,
            comment="Дополнительная информация",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deal_id"),
    )
    op.create_table(
        "product_agreement_supervisor",
        sa.Column(
            "deal_id", sa.Integer(), nullable=False, comment="ID сделки"
        ),
        sa.Column(
            "product_id", sa.Integer(), nullable=False, comment="ИД товара"
        ),
        sa.Column(
            "status_deal",
            postgresql.ENUM(
                "NEW",
                "ACCEPTED",
                "OFFER_NO",
                "OFFER_IN_AGREEMENT_SUPERVISOR",
                "OFFER_APPROVED_SUPERVISOR",
                "OFFER_DISMISSED_SUPERVISOR",
                "OFFER_SENT_CLIENT",
                "OFFER_APPROVED_CLIENT",
                "OFFER_DISMISSED_CLIENT",
                "NOT_DEFINE",
                name="deal_status_enum",
            ),
            nullable=False,
            comment="Статус обработки",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deal_id"),
    )
    # ### end Alembic commands ###

    bulk_insert(
        "deal_stages",
        ["name", "external_id", "sort_order"],
        DEAL_STAGE_VALUES,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_agreement_supervisor")
    op.drop_table("additional_info")
    op.drop_table("deals")
    op.drop_table("timeline_comments")
    op.drop_table("managers")
    op.drop_table("leads")
    op.drop_table("contacts")
    op.drop_table("companies")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_communication_channels_entity_type"),
        table_name="communication_channels",
    )
    op.drop_table("communication_channels")
    op.drop_table("departments")
    op.drop_table("deal_stages")
    op.drop_table("communication_channel_types")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS deal_stage_enum")
    op.execute("DROP TYPE IF EXISTS deal_status_enum")
