"""Add product model

Revision ID: 551a8ab5eec5
Revises: 0ddec39cb56b
Create Date: 2025-11-30 21:48:28.258731

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "551a8ab5eec5"
down_revision: Union[str, Sequence[str], None] = "0ddec39cb56b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column(
            "name", sa.String(), nullable=False, comment="Название товара"
        ),
        sa.Column(
            "code", sa.String(), nullable=True, comment="Символьный код"
        ),
        sa.Column("active", sa.Boolean(), nullable=True, comment="Активен"),
        sa.Column("sort", sa.Integer(), nullable=True, comment="Сортировка"),
        sa.Column("xml_id", sa.String(), nullable=True, comment="Внешний код"),
        sa.Column(
            "date_create",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата создания",
        ),
        sa.Column(
            "date_modify",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата изменения",
        ),
        sa.Column(
            "modified_by", sa.Integer(), nullable=True, comment="Кем изменён"
        ),
        sa.Column(
            "created_by", sa.Integer(), nullable=True, comment="Кем создан"
        ),
        sa.Column(
            "catalog_id", sa.Integer(), nullable=True, comment="Каталог"
        ),
        sa.Column("section_id", sa.Integer(), nullable=True, comment="Раздел"),
        sa.Column("price", sa.Float(), nullable=True, comment="Цена"),
        sa.Column("currency_id", sa.String(), nullable=True, comment="Валюта"),
        sa.Column("vat_id", sa.Integer(), nullable=True, comment="Ставка НДС"),
        sa.Column(
            "vat_included",
            sa.Boolean(),
            nullable=True,
            comment="НДС включён в цену",
        ),
        sa.Column(
            "measure", sa.Integer(), nullable=True, comment="Единица измерения"
        ),
        sa.Column(
            "description", sa.String(), nullable=True, comment="Описание"
        ),
        sa.Column(
            "description_type",
            sa.String(),
            nullable=True,
            comment="Тип описания",
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.external_id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "product_entities",
        sa.Column(
            "product_name",
            sa.String(),
            nullable=True,
            comment="Название товара",
        ),
        sa.Column("price", sa.Float(), nullable=True, comment="Цена"),
        sa.Column(
            "price_exclusive",
            sa.Float(),
            nullable=True,
            comment="Цена без налога со скидкой",
        ),
        sa.Column(
            "price_netto", sa.Float(), nullable=True, comment="PRICE_NETTO"
        ),
        sa.Column(
            "price_brutto", sa.Float(), nullable=True, comment="PRICE_BRUTTO"
        ),
        sa.Column("quantity", sa.Float(), nullable=True, comment="Количество"),
        sa.Column(
            "discount_type_id",
            sa.Integer(),
            nullable=True,
            comment="Тип скидки",
        ),
        sa.Column(
            "discount_rate",
            sa.Float(),
            nullable=True,
            comment="Величина скидки",
        ),
        sa.Column(
            "discount_sum", sa.Float(), nullable=True, comment="Сумма скидки"
        ),
        sa.Column("tax_rate", sa.Float(), nullable=True, comment="Налог"),
        sa.Column(
            "tax_included",
            sa.Boolean(),
            nullable=True,
            comment="Налог включен в цену",
        ),
        sa.Column(
            "customized", sa.Boolean(), nullable=True, comment="Изменен"
        ),
        sa.Column(
            "measure_code",
            sa.Integer(),
            nullable=True,
            comment="Код единицы измерения",
        ),
        sa.Column(
            "measure_name",
            sa.String(),
            nullable=True,
            comment="Единица измерения",
        ),
        sa.Column("sort", sa.Integer(), nullable=True, comment="Сортировка"),
        sa.Column("type", sa.Integer(), nullable=True, comment="TYPE"),
        sa.Column("store_id", sa.Integer(), nullable=True, comment="STORE_ID"),
        sa.Column(
            "owner_id", sa.Integer(), nullable=False, comment="ID владельца"
        ),
        sa.Column(
            "owner_type",
            sa.Enum(
                "CONTACT",
                "COMPANY",
                "LEAD",
                "DEAL",
                "INVOICE",
                "QUOTE",
                "REQUISITE",
                "ORDER",
                name="entitytypeabbr",
            ),
            nullable=False,
            comment="Тип владельца",
        ),
        sa.Column("product_id", sa.Integer(), nullable=False, comment="Товар"),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "product_properties",
        sa.Column(
            "product_id",
            sa.UUID(),
            nullable=False,
            comment="Внешний ключ к товару",
        ),
        sa.Column(
            "property_code",
            sa.String(),
            nullable=False,
            comment="Наименование свойства",
        ),
        sa.Column(
            "text_field",
            sa.String(),
            nullable=True,
            comment="Значение свойства",
        ),
        sa.Column(
            "type_field",
            sa.String(),
            nullable=True,
            comment="Значение свойства",
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(
        op.f("ix_product_properties_product_id"),
        "product_properties",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_properties_property_code"),
        "product_properties",
        ["property_code"],
        unique=False,
    )
    op.create_table(
        "product_simple_properties",
        sa.Column(
            "product_id",
            sa.UUID(),
            nullable=False,
            comment="Внешний ключ к товару",
        ),
        sa.Column(
            "property_code",
            sa.String(),
            nullable=False,
            comment="Наименование свойства",
        ),
        sa.Column(
            "value", sa.String(), nullable=True, comment="Значение свойства"
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(
        op.f("ix_product_simple_properties_product_id"),
        "product_simple_properties",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_simple_properties_property_code"),
        "product_simple_properties",
        ["property_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_product_simple_properties_property_code"),
        table_name="product_simple_properties",
    )
    op.drop_index(
        op.f("ix_product_simple_properties_product_id"),
        table_name="product_simple_properties",
    )
    op.drop_table("product_simple_properties")
    op.drop_index(
        op.f("ix_product_properties_property_code"),
        table_name="product_properties",
    )
    op.drop_index(
        op.f("ix_product_properties_product_id"),
        table_name="product_properties",
    )
    op.drop_table("product_properties")
    op.drop_table("product_entities")
    op.drop_table("products")
    # ### end Alembic commands ###
