"""Add product list in deal

Revision ID: 70c480de4d42
Revises: 551a8ab5eec5
Create Date: 2025-12-03 01:10:40.471836

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70c480de4d42"
down_revision: Union[str, Sequence[str], None] = "551a8ab5eec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deals",
        sa.Column(
            "products_list_as_string",
            sa.String(),
            nullable=True,
            comment="Список товаров преобразованном в строку",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deals", "products_list_as_string")
    # ### end Alembic commands ###
