"""Add source_key_field to supplier product model

Revision ID: c6c53cbb80ff
Revises: b04204b3843e
Create Date: 2026-02-12 20:52:00.067507

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6c53cbb80ff"
down_revision: Union[str, Sequence[str], None] = "b04204b3843e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_products",
        sa.Column(
            "source_key_field",
            sa.String(length=20),
            nullable=False,
            comment="Поле-идентификатор для сопоставления с источником",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_products", "source_key_field")
    # ### end Alembic commands ###
