"""Upd SourceColumnMapping delete unique constrains column index

Revision ID: bd0fc296b8e4
Revises: c9ea9fb6909b
Create Date: 2026-03-11 17:02:33.788398

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd0fc296b8e4"
down_revision: Union[str, Sequence[str], None] = "c9ea9fb6909b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_column_mapping_config_index"),
        "source_column_mapping",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_column_mapping_config_index"),
        "source_column_mapping",
        ["config_id", "source_column_index"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
