"""Add ProductImageContent

Revision ID: 2ebac408e8ad
Revises: 513f04b4df7e
Create Date: 2026-03-24 17:01:06.251365

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ebac408e8ad"
down_revision: Union[str, Sequence[str], None] = "513f04b4df7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images_content",
        sa.Column(
            "product_image_id",
            sa.UUID(),
            nullable=False,
            comment="Картинка товара",
        ),
        sa.Column(
            "image_data",
            sa.LargeBinary(),
            nullable=False,
            comment="Бинарные данные изображения",
        ),
        sa.Column(
            "mime_type",
            sa.String(length=100),
            nullable=True,
            comment="MIME тип изображения (image/jpeg, image/png и т.д.)",
        ),
        sa.Column(
            "file_size",
            sa.Integer(),
            nullable=True,
            comment="Размер файла в байтах",
        ),
        sa.Column(
            "file_hash",
            sa.String(length=64),
            nullable=True,
            comment="SHA256 хеш для дедупликации",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["product_image_id"], ["product_images.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_image_id"),
    )
    # ### end Alembic commands ###
    # Создаем индексы для оптимизации запросов
    op.create_index(
        "idx_product_images_content_product_image_id",
        "product_images_content",
        ["product_image_id"],
        unique=False,
    )

    op.create_index(
        "idx_product_images_content_file_hash",
        "product_images_content",
        ["file_hash"],
        unique=False,
    )

    op.create_index(
        "idx_product_images_content_created_at",
        "product_images_content",
        ["created_at"],
        unique=False,
    )

    # Оптимизация хранения LargeBinary в PostgreSQL
    # ALTER COLUMN ... SET STORAGE EXTERNAL - указывает PostgreSQL
    # хранить данные вне основной таблицы (TOAST)
    op.execute(
        "ALTER TABLE product_images_content ALTER COLUMN image_data "
        "SET STORAGE EXTERNAL"
    )

    # Дополнительная оптимизация TOAST для больших данных
    op.execute(
        "ALTER TABLE product_images_content ALTER COLUMN image_data "
        "SET COMPRESSION lz4"
    )

    # Настраиваем TOAST для оптимальной работы
    op.execute(
        "ALTER TABLE product_images_content SET (toast_tuple_target = 8160)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Удаляем индексы
    op.drop_index(
        "idx_product_images_content_created_at",
        table_name="product_images_content",
    )
    op.drop_index(
        "idx_product_images_content_file_hash",
        table_name="product_images_content",
    )
    op.drop_index(
        "idx_product_images_content_product_image_id",
        table_name="product_images_content",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_images_content")
    # ### end Alembic commands ###
