"""Add product image

Revision ID: 4c675158426d
Revises: dfc795e68dd3
Create Date: 2026-03-10 01:54:50.025802

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c675158426d"
down_revision: Union[str, Sequence[str], None] = "dfc795e68dd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column(
            "name", sa.String(), nullable=False, comment="Наименование файла"
        ),
        sa.Column("product_id", sa.Integer(), nullable=False, comment="Товар"),
        sa.Column(
            "detail_url",
            sa.String(),
            nullable=False,
            comment="Ссылка на картинку",
        ),
        sa.Column(
            "image_type", sa.String(), nullable=False, comment="Тип картинки"
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            nullable=True,
            comment="Источник данных",
        ),
        sa.Column(
            "supplier_image_url",
            sa.String(),
            nullable=True,
            comment="Ссылка поставщика на картинку",
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.add_column(
        "supplier_products",
        sa.Column(
            "more_photo",
            sa.Text(),
            nullable=True,
            comment="Дополнительные картинки",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_products", "more_photo")
    op.drop_table("product_images")
    # ### end Alembic commands ###
