"""Add supplier product

Revision ID: 5a753fdf8129
Revises: 85f1e1766d83
Create Date: 2026-02-11 22:42:15.138286

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a753fdf8129"
down_revision: Union[str, Sequence[str], None] = "85f1e1766d83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product_properties",
        "type_field",
        existing_type=sa.VARCHAR(),
        comment="Тип свойства",
        existing_comment="Значение свойства",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product_properties",
        "type_field",
        existing_type=sa.VARCHAR(),
        comment="Значение свойства",
        existing_comment="Тип свойства",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
