"""Upd SupplierProduct Name can None

Revision ID: c9ea9fb6909b
Revises: 35ac667c1745
Create Date: 2026-03-11 15:50:59.541427

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9ea9fb6909b"
down_revision: Union[str, Sequence[str], None] = "35ac667c1745"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplier_products",
        "name",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_comment="Название товара",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplier_products",
        "name",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_comment="Название товара",
    )
    # ### end Alembic commands ###
