"""Add source_key_field to ImportConfig model

Revision ID: dab491f8a066
Revises: 818cfbcec359
Create Date: 2026-02-12 21:05:11.869071

"""

from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dab491f8a066"
down_revision: Union[str, Sequence[str], None] = "818cfbcec359"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
