"""Add crm_value_previous to log

Revision ID: 5be3142e7ae6
Revises: 39838341cfcb
Create Date: 2026-04-03 15:56:57.481555

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5be3142e7ae6"
down_revision: Union[str, Sequence[str], None] = "39838341cfcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_product_change_log",
        sa.Column(
            "crm_value_previous",
            sa.Text(),
            nullable=True,
            comment="Предыдущее значение в CRM",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_product_change_log", "crm_value_previous")
    # ### end Alembic commands ###
