"""Upd supplier product

Revision ID: 1fef2a92e5ab
Revises: 5a753fdf8129
Create Date: 2026-02-11 23:13:00.391846

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fef2a92e5ab"
down_revision: Union[str, Sequence[str], None] = "5a753fdf8129"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_import_config",
        sa.Column(
            "source",
            sa.String(length=20),
            nullable=False,
            comment="Источник данных",
        ),
        sa.Column(
            "config_name",
            sa.String(length=255),
            nullable=True,
            comment="Название конфигурации",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Активность конфигурации",
        ),
        sa.Column(
            "file_format",
            sa.String(length=10),
            nullable=True,
            comment="Формат файла: CSV, XLSX, XML и т.д.",
        ),
        sa.Column(
            "encoding",
            sa.String(length=20),
            nullable=True,
            comment="Кодировка файла, например UTF-8",
        ),
        sa.Column(
            "delimiter",
            sa.String(length=5),
            nullable=True,
            comment="Разделитель для CSV.",
        ),
        sa.Column(
            "header_row_index",
            sa.Integer(),
            nullable=True,
            comment="Номер строки с заголовками",
        ),
        sa.Column(
            "data_start_row",
            sa.Integer(),
            nullable=True,
            comment="Номер начала данных",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "config_name", name="uq_import_config_source_name"
        ),
    )
    op.create_table(
        "source_column_mapping",
        sa.Column(
            "config_id",
            sa.UUID(),
            nullable=False,
            comment="Конфигурация источника данных",
        ),
        sa.Column(
            "target_field",
            sa.String(length=100),
            nullable=False,
            comment="Имя поля в базе данных",
        ),
        sa.Column(
            "source_column_name",
            sa.String(length=255),
            nullable=False,
            comment="Имя столбца в загружаемом файле",
        ),
        sa.Column(
            "source_column_index",
            sa.Integer(),
            nullable=False,
            comment="Номер столбца в загружаемом файле",
        ),
        sa.Column(
            "force_import",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Перегружать в CRM без проверки",
        ),
        sa.Column(
            "data_type",
            sa.String(length=20),
            nullable=True,
            comment="Тип данных: string, integer, decimal, date и т.д.",
        ),
        sa.Column(
            "transformation_rule",
            sa.String(length=50),
            nullable=True,
            comment="Правило трансформации (regexp, формула)",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=False,
            comment="Для UI и порядка обработки",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["config_id"], ["source_import_config.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "config_id",
            "source_column_index",
            name="uq_column_mapping_config_index",
        ),
        sa.UniqueConstraint(
            "config_id", "target_field", name="uq_column_mapping_config_target"
        ),
    )
    op.create_index(
        "ix_column_mappings_config_id",
        "source_column_mapping",
        ["config_id"],
        unique=False,
    )
    op.create_index(
        "ix_column_mappings_target_field",
        "source_column_mapping",
        ["target_field"],
        unique=False,
    )
    op.create_table(
        "supplier_products",
        sa.Column(
            "name",
            sa.String(length=500),
            nullable=False,
            comment="Название товара",
        ),
        sa.Column(
            "code",
            sa.String(length=100),
            nullable=True,
            comment="Символьный код",
        ),
        sa.Column("active", sa.Boolean(), nullable=True, comment="Активен"),
        sa.Column("sort", sa.Integer(), nullable=True, comment="Сортировка"),
        sa.Column(
            "xml_id",
            sa.String(length=100),
            nullable=True,
            comment="Внешний код",
        ),
        sa.Column(
            "price",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Цена",
        ),
        sa.Column(
            "currency_id",
            sa.String(length=10),
            nullable=True,
            comment="Валюта",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание"),
        sa.Column(
            "description_type",
            sa.String(length=10),
            nullable=True,
            comment="Тип описания",
        ),
        sa.Column(
            "link", sa.String(length=500), nullable=True, comment="Ссылка"
        ),
        sa.Column(
            "original_name",
            sa.String(length=500),
            nullable=True,
            comment="Оригинальное название",
        ),
        sa.Column(
            "standards",
            sa.String(length=500),
            nullable=True,
            comment="Стандарты",
        ),
        sa.Column(
            "article", sa.String(length=255), nullable=True, comment="Артикул"
        ),
        sa.Column(
            "supplier_category",
            sa.String(length=150),
            nullable=True,
            comment="Категория в системе поставщика",
        ),
        sa.Column(
            "supplier_subcategory",
            sa.String(length=150),
            nullable=True,
            comment="Подкатегория в системе поставщика",
        ),
        sa.Column(
            "detail_picture",
            sa.String(length=500),
            nullable=True,
            comment="Детальная картинка (путь)",
        ),
        sa.Column(
            "detail_picture_description",
            sa.String(length=255),
            nullable=True,
            comment="Описание для детальной картинки",
        ),
        sa.Column(
            "preview_picture",
            sa.String(length=500),
            nullable=True,
            comment="Картинка для анонса (путь)",
        ),
        sa.Column(
            "preview_picture_description",
            sa.String(length=255),
            nullable=True,
            comment="Описание для картинки анонса",
        ),
        sa.Column(
            "preview_text",
            sa.Text(),
            nullable=True,
            comment="Описание для анонса",
        ),
        sa.Column(
            "preview_text_type",
            sa.String(length=10),
            nullable=True,
            comment="Тип описания для анонса",
        ),
        sa.Column(
            "availability_status",
            sa.String(length=50),
            nullable=True,
            comment="Статус наличия",
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Остаток",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            nullable=False,
            comment="Источник данных",
        ),
        sa.Column(
            "is_validated",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Флаг обработки позиции",
        ),
        sa.Column(
            "should_export_to_crm",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Выгружать в CRM",
        ),
        sa.Column(
            "internal_section_id",
            sa.Integer(),
            nullable=True,
            comment="Раздел в CRM",
        ),
        sa.Column(
            "product_id",
            sa.UUID(),
            nullable=True,
            comment="Идентификатор связанного товара в системе",
        ),
        sa.Column(
            "preview_for_offer",
            sa.Text(),
            nullable=True,
            comment="Анонс для предложенияя",
        ),
        sa.Column(
            "description_for_offer",
            sa.Text(),
            nullable=True,
            comment="Описание для предложения",
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.CheckConstraint(
            "price >= 0", name="ck_supplier_products_price_positive"
        ),
        sa.CheckConstraint(
            "quantity >= 0", name="ck_supplier_products_quantity_positive"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("source", "code", name="uq_supplier_source_code"),
    )
    op.create_index(
        "ix_supplier_products_code",
        "supplier_products",
        ["code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_products_product_id"),
        "supplier_products",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        "ix_supplier_products_source",
        "supplier_products",
        ["source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_products_supplier_category"),
        "supplier_products",
        ["supplier_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_products_supplier_subcategory"),
        "supplier_products",
        ["supplier_subcategory"],
        unique=False,
    )
    op.create_table(
        "supplier_characteristics",
        sa.Column(
            "name",
            sa.String(length=500),
            nullable=False,
            comment="Название характеристики",
        ),
        sa.Column(
            "value",
            sa.String(length=255),
            nullable=True,
            comment="Значение характеристики",
        ),
        sa.Column(
            "unit",
            sa.String(length=255),
            nullable=True,
            comment="Единица измерения",
        ),
        sa.Column(
            "supplier_product_id",
            sa.UUID(),
            nullable=False,
            comment="Ссылка на товар поставщика",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_product_id"],
            ["supplier_products.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supplier_complects",
        sa.Column(
            "name",
            sa.String(length=500),
            nullable=False,
            comment="Название комплектующего",
        ),
        sa.Column(
            "code",
            sa.String(length=100),
            nullable=True,
            comment="Символьный код",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание"),
        sa.Column(
            "specifications", sa.Text(), nullable=True, comment="Спецификации"
        ),
        sa.Column(
            "supplier_product_id",
            sa.UUID(),
            nullable=False,
            comment="Ссылка на товар поставщика",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_product_id"],
            ["supplier_products.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_complects_code"),
        "supplier_complects",
        ["code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_supplier_complects_code"), table_name="supplier_complects"
    )
    op.drop_table("supplier_complects")
    op.drop_table("supplier_characteristics")
    op.drop_index(
        op.f("ix_supplier_products_supplier_subcategory"),
        table_name="supplier_products",
    )
    op.drop_index(
        op.f("ix_supplier_products_supplier_category"),
        table_name="supplier_products",
    )
    op.drop_index(
        "ix_supplier_products_source", table_name="supplier_products"
    )
    op.drop_index(
        op.f("ix_supplier_products_product_id"), table_name="supplier_products"
    )
    op.drop_index("ix_supplier_products_code", table_name="supplier_products")
    op.drop_table("supplier_products")
    op.drop_index(
        "ix_column_mappings_target_field", table_name="source_column_mapping"
    )
    op.drop_index(
        "ix_column_mappings_config_id", table_name="source_column_mapping"
    )
    op.drop_table("source_column_mapping")
    op.drop_table("source_import_config")
    # ### end Alembic commands ###
