"""Add brand to supplier product

Revision ID: 513f04b4df7e
Revises: bd0fc296b8e4
Create Date: 2026-03-13 16:12:55.433312

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "513f04b4df7e"
down_revision: Union[str, Sequence[str], None] = "bd0fc296b8e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_products",
        sa.Column(
            "brend", sa.String(length=150), nullable=True, comment="Бренд"
        ),
    )
    op.create_index(
        op.f("ix_supplier_products_brend"),
        "supplier_products",
        ["brend"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_supplier_products_brend"), table_name="supplier_products"
    )
    op.drop_column("supplier_products", "brend")
    # ### end Alembic commands ###
