"""Add measure to supplier product

Revision ID: 0d8f34934430
Revises: 278e470fed86
Create Date: 2026-04-22 14:14:03.654091

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d8f34934430"
down_revision: Union[str, Sequence[str], None] = "278e470fed86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_products",
        sa.Column(
            "measure", sa.Integer(), nullable=True, comment="Единица измерения"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_products", "measure")
    # ### end Alembic commands ###
