"""Add more_photo_process to supplier_product

Revision ID: 7b01b840c613
Revises: 2ebac408e8ad
Create Date: 2026-03-26 13:15:41.291039

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b01b840c613"
down_revision: Union[str, Sequence[str], None] = "2ebac408e8ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_product_images_content_created_at"),
        table_name="product_images_content",
    )
    op.drop_index(
        op.f("idx_product_images_content_file_hash"),
        table_name="product_images_content",
    )
    op.drop_index(
        op.f("idx_product_images_content_product_image_id"),
        table_name="product_images_content",
    )
    op.add_column(
        "supplier_products",
        sa.Column(
            "more_photo_process",
            sa.Text(),
            nullable=True,
            comment="Обработанные доп картинки",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_products", "more_photo_process")
    op.create_index(
        op.f("idx_product_images_content_product_image_id"),
        "product_images_content",
        ["product_image_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_product_images_content_file_hash"),
        "product_images_content",
        ["file_hash"],
        unique=False,
    )
    op.create_index(
        op.f("idx_product_images_content_created_at"),
        "product_images_content",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
