"""Add detail picture processed to supplier product

Revision ID: 278e470fed86
Revises: 5be3142e7ae6
Create Date: 2026-04-06 16:51:08.793174

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "278e470fed86"
down_revision: Union[str, Sequence[str], None] = "5be3142e7ae6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_products",
        sa.Column(
            "detail_picture_process",
            sa.Text(),
            nullable=True,
            comment="Обработанная детальная картинка",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_products", "detail_picture_process")
    # ### end Alembic commands ###
