"""Add sync_with_crm in ImportColumnMapping

Revision ID: af460b0c1d3b
Revises: dab491f8a066
Create Date: 2026-02-17 12:40:03.854780

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af460b0c1d3b"
down_revision: Union[str, Sequence[str], None] = "dab491f8a066"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_column_mapping",
        sa.Column(
            "sync_with_crm",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Участвует в синхронизации с CRM",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_column_mapping", "sync_with_crm")
    # ### end Alembic commands ###
