"""Add failure_reason to lead

Revision ID: 06d73f15013f
Revises: 481bb8c04f0b
Create Date: 2026-03-03 01:01:39.919410

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06d73f15013f"
down_revision: Union[str, Sequence[str], None] = "481bb8c04f0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

lead_failure_enum = postgresql.ENUM(
    "SPAM",
    "WRONG_CONTACT",
    "NO_ANSWER",
    "INVALID_CONTACT_DATA",
    "TEST_LEAD",
    "DUPLICATE",
    "OTHER",
    name="lead_failure_enum",
    create_type=True,
)


def upgrade() -> None:
    """Upgrade schema."""

    lead_failure_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "leads",
        sa.Column(
            "failure_reason",
            lead_failure_enum,
            nullable=True,
            comment="Причина провала лида",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("leads", "failure_reason")
    # ### end Alembic commands ###
    lead_failure_enum.drop(op.get_bind(), checkfirst=True)
