"""Add Productsection

Revision ID: 9d1471a3222d
Revises: af460b0c1d3b
Create Date: 2026-02-18 22:20:52.822024

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d1471a3222d"
down_revision: Union[str, Sequence[str], None] = "af460b0c1d3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productsections",
        sa.Column(
            "catalog_id", sa.Integer(), nullable=True, comment="Каталог"
        ),
        sa.Column("xml_id", sa.String(), nullable=True, comment="Внешний код"),
        sa.Column(
            "code", sa.String(), nullable=True, comment="Символьный код"
        ),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False, comment="Название"),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["productsections.external_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.alter_column(
        "source_import_config",
        "header_row_index",
        existing_type=sa.INTEGER(),
        comment="Номер строки с заголовками. Нумерация с 0.",
        existing_comment="Номер строки с заголовками",
        existing_nullable=True,
    )
    op.alter_column(
        "source_import_config",
        "data_start_row",
        existing_type=sa.INTEGER(),
        comment="Номер начала данных. Нумерация с 0.",
        existing_comment="Номер начала данных",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "source_import_config",
        "data_start_row",
        existing_type=sa.INTEGER(),
        comment="Номер начала данных",
        existing_comment="Номер начала данных. Нумерация с 0.",
        existing_nullable=True,
    )
    op.alter_column(
        "source_import_config",
        "header_row_index",
        existing_type=sa.INTEGER(),
        comment="Номер строки с заголовками",
        existing_comment="Номер строки с заголовками. Нумерация с 0.",
        existing_nullable=True,
    )
    op.drop_table("productsections")
    # ### end Alembic commands ###
