"""Add configuration json to product

Revision ID: 24eef2057a2d
Revises: 9a53367dfd13
Create Date: 2026-03-30 21:11:39.721794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24eef2057a2d"
down_revision: Union[str, Sequence[str], None] = "9a53367dfd13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "configuration",
            sa.JSON(),
            nullable=True,
            comment="Характеристики в списке",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "configuration")
    # ### end Alembic commands ###
