"""Upd SupplierProductChangeLog

Revision ID: 35ac667c1745
Revises: 7a0961fc232c
Create Date: 2026-03-11 15:44:33.966691

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35ac667c1745"
down_revision: Union[str, Sequence[str], None] = "7a0961fc232c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_supplier_products_external_id",
        "supplier_products",
        ["external_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_supplier_source_external_id",
        "supplier_products",
        ["source", "external_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_supplier_source_external_id", "supplier_products", type_="unique"
    )
    op.drop_index(
        "ix_supplier_products_external_id", table_name="supplier_products"
    )
    # ### end Alembic commands ###
