"""Add source_key_field to supplier product model

Revision ID: 818cfbcec359
Revises: c6c53cbb80ff
Create Date: 2026-02-12 20:57:31.348965

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "818cfbcec359"
down_revision: Union[str, Sequence[str], None] = "c6c53cbb80ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_import_config",
        sa.Column(
            "source_key_field",
            sa.String(length=20),
            nullable=False,
            server_default="external_id",
            comment="Поле-идентификатор для сопоставления с источником",
        ),
    )
    op.drop_column("supplier_products", "source_key_field")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_products",
        sa.Column(
            "source_key_field",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            comment="Поле-идентификатор для сопоставления с источником",
        ),
    )
    op.drop_column("source_import_config", "source_key_field")
    # ### end Alembic commands ###
