"""Add SupplierProductChangeLog

Revision ID: 7a0961fc232c
Revises: 4c675158426d
Create Date: 2026-03-11 01:24:37.207903

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a0961fc232c"
down_revision: Union[str, Sequence[str], None] = "4c675158426d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier_product_change_log",
        sa.Column(
            "supplier_product_id",
            sa.UUID(),
            nullable=False,
            comment="ID товара поставщика",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            nullable=False,
            comment="Источник данных",
        ),
        sa.Column(
            "config_name",
            sa.String(length=100),
            nullable=True,
            comment="Источник импорта (название файла или конфига)",
        ),
        sa.Column(
            "field_name",
            sa.String(length=50),
            nullable=False,
            comment="Название измененного поля",
        ),
        sa.Column(
            "old_value",
            sa.Text(),
            nullable=True,
            comment="Значение ДО изменения",
        ),
        sa.Column(
            "new_value",
            sa.Text(),
            nullable=True,
            comment="Значение ПОСЛЕ изменения",
        ),
        sa.Column(
            "value_type",
            sa.String(),
            nullable=True,
            comment="Тип значения (int, float, str, bool)",
        ),
        sa.Column(
            "is_processed",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Проверено вручную?",
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Когда проверили",
        ),
        sa.Column(
            "processed_by_user_id",
            sa.Integer(),
            nullable=True,
            comment="ID пользователя, который проверил",
        ),
        sa.Column(
            "comment",
            sa.Text(),
            nullable=True,
            comment="Комментарий менеджера при проверке",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_product_id"],
            ["supplier_products.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_product_change_log_supplier_product_id"),
        "supplier_product_change_log",
        ["supplier_product_id"],
        unique=False,
    )
    op.alter_column(
        "supplier_products",
        "external_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="ID во внешней системе",
    )
    op.drop_constraint(
        op.f("supplier_products_external_id_key"),
        "supplier_products",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("supplier_products_external_id_key"),
        "supplier_products",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "supplier_products",
        "external_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="ID во внешней системе",
    )
    op.drop_index(
        op.f("ix_supplier_product_change_log_supplier_product_id"),
        table_name="supplier_product_change_log",
    )
    op.drop_table("supplier_product_change_log")
    # ### end Alembic commands ###
