"""Add description_for_print to supplier product

Revision ID: 39838341cfcb
Revises: 03bc8f2bd2c0
Create Date: 2026-04-03 04:18:42.958714

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39838341cfcb"
down_revision: Union[str, Sequence[str], None] = "03bc8f2bd2c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_products",
        sa.Column(
            "description_for_print",
            sa.Text(),
            nullable=True,
            comment="Описание загруженное в Битрикс",
        ),
    )
    op.alter_column(
        "supplier_products",
        "external_id",
        existing_type=sa.INTEGER(),
        comment="ID во внешней системе поставщика",
        existing_comment="ID во внешней системе",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplier_products",
        "external_id",
        existing_type=sa.INTEGER(),
        comment="ID во внешней системе",
        existing_comment="ID во внешней системе поставщика",
        existing_nullable=True,
    )
    op.drop_column("supplier_products", "description_for_print")
    # ### end Alembic commands ###
