"""Add UserAuth

Revision ID: f18a33e3456a
Revises: 7b01b840c613
Create Date: 2026-03-27 23:59:02.257136

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f18a33e3456a"
down_revision: Union[str, Sequence[str], None] = "7b01b840c613"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_auths",
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="ID пользователя"
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
            comment="Хеш пароля",
        ),
        sa.Column(
            "role",
            sa.String(length=10),
            nullable=False,
            comment="Роль пользователя",
        ),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            comment="Email подтвержден",
        ),
        sa.Column(
            "last_login_attempt",
            sa.DateTime(),
            nullable=True,
            comment="Последняя попытка входа",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted_in_bitrix",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Удалён в Битрикс",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_auths")
    # ### end Alembic commands ###
