"""Add specifications json to product

Revision ID: 9a53367dfd13
Revises: 81badc2d3fe7
Create Date: 2026-03-30 18:02:28.456944

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a53367dfd13"
down_revision: Union[str, Sequence[str], None] = "81badc2d3fe7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "specifications",
            sa.JSON(),
            nullable=True,
            comment="Характеристики в списке",
        ),
    )
    op.alter_column(
        "users",
        "employment_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Дата принятия на работу",
        existing_comment="Новая дата",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "employment_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Новая дата",
        existing_comment="Дата принятия на работу",
        existing_nullable=True,
    )
    op.drop_column("products", "specifications")
    # ### end Alembic commands ###
