"""Add fields to change_log

Revision ID: 03bc8f2bd2c0
Revises: 24eef2057a2d
Create Date: 2026-04-01 18:07:13.362208

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03bc8f2bd2c0"
down_revision: Union[str, Sequence[str], None] = "24eef2057a2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_product_change_log",
        sa.Column(
            "loaded_value",
            sa.Text(),
            nullable=True,
            comment="Загруженное значение",
        ),
    )
    op.add_column(
        "supplier_product_change_log",
        sa.Column(
            "force_import",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Перегружено в CRM без проверки",
        ),
    )
    op.add_column(
        "supplier_product_change_log",
        sa.Column(
            "loaded_by_user_id",
            sa.Integer(),
            nullable=True,
            comment="ID пользователя, который загрузил",
        ),
    )
    op.alter_column(
        "supplier_product_change_log",
        "is_processed",
        existing_type=sa.BOOLEAN(),
        comment="Обработано",
        existing_comment="Проверено вручную?",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplier_product_change_log",
        "is_processed",
        existing_type=sa.BOOLEAN(),
        comment="Проверено вручную?",
        existing_comment="Обработано",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_column("supplier_product_change_log", "loaded_by_user_id")
    op.drop_column("supplier_product_change_log", "force_import")
    op.drop_column("supplier_product_change_log", "loaded_value")
    # ### end Alembic commands ###
