"""Add needs_review to supplier

Revision ID: 481bb8c04f0b
Revises: 9d1471a3222d
Create Date: 2026-03-02 15:19:26.628573

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "481bb8c04f0b"
down_revision: Union[str, Sequence[str], None] = "9d1471a3222d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_products",
        sa.Column(
            "needs_review",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Требует ручной обработки",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_products", "needs_review")
    # ### end Alembic commands ###
