"""Upd type last_login_attemp UserAuth

Revision ID: 81badc2d3fe7
Revises: f18a33e3456a
Create Date: 2026-03-28 12:49:32.692388

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "81badc2d3fe7"
down_revision: Union[str, Sequence[str], None] = "f18a33e3456a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_auths",
        "last_login_attempt",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_comment="Последняя попытка входа",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_auths",
        "last_login_attempt",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="Последняя попытка входа",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
