"""Upd supplier product external_id

Revision ID: b04204b3843e
Revises: 1fef2a92e5ab
Create Date: 2026-02-12 13:05:12.393001

"""

from typing import Sequence, Union

# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b04204b3843e"
down_revision: Union[str, Sequence[str], None] = "1fef2a92e5ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
